name:                watch-trace
version:             0.1.0.0
github:              "Avi-D-coder/watch-trace"
license:             BSD3
author:              "Avi Dessauer"
maintainer:          "avi.the.coder@gmail.com"
copyright:           "2020"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Avi-D-coder/watch-trace#readme>

dependencies:
- base >= 4.7 && < 5
- ghc-heap-view >= 0.6
- fgl >= 5
- text
- unordered-containers
- hashable
- fused-effects

ghc-options:
- -O2
- -flate-specialise
- -fexpose-all-unfoldings
- -fspecialize-aggressively
- -Wall
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -fno-warn-unused-imports
- -fno-warn-unused-binds
- -fno-warn-name-shadowing

library:
  source-dirs: src

executables:
  watch-trace-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - watch-trace

tests:
  watch-trace-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - watch-trace
